`include "project_defs.vh"
// Lane order: PTB210,HMP,EPSILON,BMP390,SHT45,TFA1500,AI8.
// SDA/SCL drive_low outputs feed top-level open-drain IOBUF controls.
module member3_sensor_bank #(
    parameter integer SYS_CLK_HZ=100000000,FIFO_DEPTH=256,PTB_BOOT_MS=2000,EPSILON_PASSIVE_MS=2500
)(
    input wire sys_clk,rst_sys_n,
    input wire [63:0] timestamp_now,input wire time_sync_valid,input wire [31:0] time_sync_seq,
    input wire sync_event_pulse,
    input wire cfg_valid,cfg_write,input wire [31:0] cfg_addr,cfg_wdata,input wire [3:0] cfg_wstrb,
    output wire cfg_ready,output reg [31:0] cfg_rdata,output wire cfg_error,
    input wire ptb_rxd,output wire ptb_txd,
    input wire rs485_rxd,output wire rs485_txd,rs485_de,
    input wire epsilon_rxd,output wire epsilon_txd,
    input wire tfa_hf_rxd,tfa_lf_rxd,output wire tfa_txd,
    input wire scl_i,sda_i,bmp_int,output wire scl_drive_low,sda_drive_low,
    output wire [63:0] gnss_time_tag,output wire gnss_time_tag_valid,
    output wire [6:0] m_valid,input wire [6:0] m_ready,
    output wire [223:0] m_data,output wire [27:0] m_keep,
    output wire [6:0] m_sof,m_last,
    output wire [111:0] m_source_id,m_msg_id,
    output wire [447:0] m_timestamp,output wire [223:0] m_cycle_id,m_flags,
    output wire [6:0] device_online,
    output wire [223:0] device_error,device_drop_count,device_fifo_level,
    output wire [27:0] cfg_error_code
);
    wire [6:0] ready,error;
    wire [223:0] rdata;
    integer c;
    assign cfg_ready=|ready;
    assign cfg_error=|(error&ready);
    always @*begin
        cfg_rdata=0;
        for(c=0;c<7;c=c+1)if(ready[c])cfg_rdata=cfg_rdata|rdata[c*32+:32];
    end
    wire [1:0] i_valid,i_ready,i_done;
    wire [13:0] i_addr;
    wire [11:0] i_write_len,i_read_len;
    wire [511:0] i_write_data,i_read_data;
    wire [5:0] i_error;
    wire req_valid,req_ready,done,busy;
    wire [6:0] req_addr;
    wire [5:0] req_write_len,req_read_len;
    wire [255:0] req_write_data,read_data;
    wire [2:0] bus_error;
    wire [1:0] bus_request,bus_busy,bus_grant,bus_rxd,bus_txd,bus_de;
    rs485_transaction_arbiter u_rs485_arbiter(
        .clk(sys_clk),.rst_n(rst_sys_n),.request(bus_request),.busy(bus_busy),
        .txd(bus_txd),.de(bus_de),.uart_rxd(rs485_rxd),.grant(bus_grant),
        .rxd(bus_rxd),.uart_txd(rs485_txd),.rs485_de(rs485_de));
    ptb210_rs232 #(.SYS_CLK_HZ(SYS_CLK_HZ),.FIFO_DEPTH(FIFO_DEPTH),.BOOT_DELAY_MS(PTB_BOOT_MS),.RESET_DELAY_MS(PTB_BOOT_MS)) u_0(
        .sys_clk(sys_clk),
        .rst_sys_n(rst_sys_n),
        .timestamp_now(timestamp_now),
        .time_sync_valid(time_sync_valid),
        .time_sync_seq(time_sync_seq),
        .cfg_valid(cfg_valid),
        .cfg_write(cfg_write),
        .cfg_addr(cfg_addr),
        .cfg_wdata(cfg_wdata),
        .cfg_wstrb(cfg_wstrb),
        .uart_rxd(ptb_rxd),
        .uart_txd(ptb_txd),
        .cfg_ready(ready[0]),
        .cfg_error(error[0]),
        .cfg_error_code(cfg_error_code[0+:4]),
        .cfg_rdata(rdata[0+:32]),
        .m_valid(m_valid[0]),
        .m_ready(m_ready[0]),
        .m_data(m_data[0+:32]),
        .m_keep(m_keep[0+:4]),
        .m_sof(m_sof[0]),
        .m_last(m_last[0]),
        .m_source_id(m_source_id[0+:16]),
        .m_msg_id(m_msg_id[0+:16]),
        .m_timestamp(m_timestamp[0+:64]),
        .m_cycle_id(m_cycle_id[0+:32]),
        .m_flags(m_flags[0+:32]),
        .monitor_online(device_online[0]),
        .monitor_errors(device_error[0+:32]),
        .monitor_drop_count(device_drop_count[0+:32]),
        .monitor_fifo_level(device_fifo_level[0+:32]));
    hmp_modbus_rs485 #(.SYS_CLK_HZ(SYS_CLK_HZ),.FIFO_DEPTH(FIFO_DEPTH),.SHARED_BUS(1)) u_1(
        .sys_clk(sys_clk),
        .rst_sys_n(rst_sys_n),
        .timestamp_now(timestamp_now),
        .time_sync_valid(time_sync_valid),
        .time_sync_seq(time_sync_seq),
        .cfg_valid(cfg_valid),
        .cfg_write(cfg_write),
        .cfg_addr(cfg_addr),
        .cfg_wdata(cfg_wdata),
        .cfg_wstrb(cfg_wstrb),
        .uart_rxd(bus_rxd[0]),
        .uart_txd(bus_txd[0]),
        .rs485_de(bus_de[0]),
        .bus_request(bus_request[0]),
        .bus_busy(bus_busy[0]),
        .bus_grant(bus_grant[0]),
        .cfg_ready(ready[1]),
        .cfg_error(error[1]),
        .cfg_error_code(cfg_error_code[4+:4]),
        .cfg_rdata(rdata[32+:32]),
        .m_valid(m_valid[1]),
        .m_ready(m_ready[1]),
        .m_data(m_data[32+:32]),
        .m_keep(m_keep[4+:4]),
        .m_sof(m_sof[1]),
        .m_last(m_last[1]),
        .m_source_id(m_source_id[16+:16]),
        .m_msg_id(m_msg_id[16+:16]),
        .m_timestamp(m_timestamp[64+:64]),
        .m_cycle_id(m_cycle_id[32+:32]),
        .m_flags(m_flags[32+:32]),
        .online(device_online[1]),
        .errors(device_error[32+:32]),
        .drop_count(device_drop_count[32+:32]),
        .fifo_level(device_fifo_level[32+:32]));
    epsilon_rs232 #(.SYS_CLK_HZ(SYS_CLK_HZ),.FIFO_DEPTH(FIFO_DEPTH),.PASSIVE_MS(EPSILON_PASSIVE_MS)) u_2(
        .sys_clk(sys_clk),
        .rst_sys_n(rst_sys_n),
        .timestamp_now(timestamp_now),
        .time_sync_valid(time_sync_valid),
        .time_sync_seq(time_sync_seq),
        .cfg_valid(cfg_valid),
        .cfg_write(cfg_write),
        .cfg_addr(cfg_addr),
        .cfg_wdata(cfg_wdata),
        .cfg_wstrb(cfg_wstrb),
        .uart_rxd(epsilon_rxd),
        .uart_txd(epsilon_txd),
        .sync_event_pulse(sync_event_pulse),
        .gnss_time_tag(gnss_time_tag),
        .gnss_time_tag_valid(gnss_time_tag_valid),
        .cfg_ready(ready[2]),
        .cfg_error(error[2]),
        .cfg_error_code(cfg_error_code[8+:4]),
        .cfg_rdata(rdata[64+:32]),
        .m_valid(m_valid[2]),
        .m_ready(m_ready[2]),
        .m_data(m_data[64+:32]),
        .m_keep(m_keep[8+:4]),
        .m_sof(m_sof[2]),
        .m_last(m_last[2]),
        .m_source_id(m_source_id[32+:16]),
        .m_msg_id(m_msg_id[32+:16]),
        .m_timestamp(m_timestamp[128+:64]),
        .m_cycle_id(m_cycle_id[64+:32]),
        .m_flags(m_flags[64+:32]),
        .online(device_online[2]),
        .errors(device_error[64+:32]),
        .drop_count(device_drop_count[64+:32]),
        .fifo_level(device_fifo_level[64+:32]));
    bmp390_driver #(.SYS_CLK_HZ(SYS_CLK_HZ),.FIFO_DEPTH(FIFO_DEPTH)) u_3(
        .sys_clk(sys_clk),
        .rst_sys_n(rst_sys_n),
        .timestamp_now(timestamp_now),
        .time_sync_valid(time_sync_valid),
        .time_sync_seq(time_sync_seq),
        .cfg_valid(cfg_valid),
        .cfg_write(cfg_write),
        .cfg_addr(cfg_addr),
        .cfg_wdata(cfg_wdata),
        .cfg_wstrb(cfg_wstrb),
        .bmp_int(bmp_int),
        .cfg_ready(ready[3]),
        .cfg_error(error[3]),
        .cfg_error_code(cfg_error_code[12+:4]),
        .cfg_rdata(rdata[96+:32]),
        .m_valid(m_valid[3]),
        .m_ready(m_ready[3]),
        .m_data(m_data[96+:32]),
        .m_keep(m_keep[12+:4]),
        .m_sof(m_sof[3]),
        .m_last(m_last[3]),
        .m_source_id(m_source_id[48+:16]),
        .m_msg_id(m_msg_id[48+:16]),
        .m_timestamp(m_timestamp[192+:64]),
        .m_cycle_id(m_cycle_id[96+:32]),
        .m_flags(m_flags[96+:32]),
        .online(device_online[3]),
        .errors(device_error[96+:32]),
        .drop_count(device_drop_count[96+:32]),
        .fifo_level(device_fifo_level[96+:32]),
        .req_valid(i_valid[0]),
        .req_ready(i_ready[0]),
        .req_addr(i_addr[0+:7]),
        .req_write_len(i_write_len[0+:6]),
        .req_read_len(i_read_len[0+:6]),
        .req_write_data(i_write_data[0+:256]),
        .done(i_done[0]),
        .error(i_error[0+:3]),
        .read_data(i_read_data[0+:256]));
    sht45_driver #(.SYS_CLK_HZ(SYS_CLK_HZ),.FIFO_DEPTH(FIFO_DEPTH)) u_4(
        .sys_clk(sys_clk),
        .rst_sys_n(rst_sys_n),
        .timestamp_now(timestamp_now),
        .time_sync_valid(time_sync_valid),
        .time_sync_seq(time_sync_seq),
        .cfg_valid(cfg_valid),
        .cfg_write(cfg_write),
        .cfg_addr(cfg_addr),
        .cfg_wdata(cfg_wdata),
        .cfg_wstrb(cfg_wstrb),
        .cfg_ready(ready[4]),
        .cfg_error(error[4]),
        .cfg_error_code(cfg_error_code[16+:4]),
        .cfg_rdata(rdata[128+:32]),
        .m_valid(m_valid[4]),
        .m_ready(m_ready[4]),
        .m_data(m_data[128+:32]),
        .m_keep(m_keep[16+:4]),
        .m_sof(m_sof[4]),
        .m_last(m_last[4]),
        .m_source_id(m_source_id[64+:16]),
        .m_msg_id(m_msg_id[64+:16]),
        .m_timestamp(m_timestamp[256+:64]),
        .m_cycle_id(m_cycle_id[128+:32]),
        .m_flags(m_flags[128+:32]),
        .online(device_online[4]),
        .errors(device_error[128+:32]),
        .drop_count(device_drop_count[128+:32]),
        .fifo_level(device_fifo_level[128+:32]),
        .req_valid(i_valid[1]),
        .req_ready(i_ready[1]),
        .req_addr(i_addr[7+:7]),
        .req_write_len(i_write_len[6+:6]),
        .req_read_len(i_read_len[6+:6]),
        .req_write_data(i_write_data[256+:256]),
        .done(i_done[1]),
        .error(i_error[3+:3]),
        .read_data(i_read_data[256+:256]));
    tfa1500_uart #(.SYS_CLK_HZ(SYS_CLK_HZ),.FIFO_DEPTH(FIFO_DEPTH)) u_5(
        .sys_clk(sys_clk),
        .rst_sys_n(rst_sys_n),
        .timestamp_now(timestamp_now),
        .time_sync_valid(time_sync_valid),
        .time_sync_seq(time_sync_seq),
        .cfg_valid(cfg_valid),
        .cfg_write(cfg_write),
        .cfg_addr(cfg_addr),
        .cfg_wdata(cfg_wdata),
        .cfg_wstrb(cfg_wstrb),
        .hf_rxd(tfa_hf_rxd),
        .lf_rxd(tfa_lf_rxd),
        .uart_txd(tfa_txd),
        .cfg_ready(ready[5]),
        .cfg_error(error[5]),
        .cfg_error_code(cfg_error_code[20+:4]),
        .cfg_rdata(rdata[160+:32]),
        .m_valid(m_valid[5]),
        .m_ready(m_ready[5]),
        .m_data(m_data[160+:32]),
        .m_keep(m_keep[20+:4]),
        .m_sof(m_sof[5]),
        .m_last(m_last[5]),
        .m_source_id(m_source_id[80+:16]),
        .m_msg_id(m_msg_id[80+:16]),
        .m_timestamp(m_timestamp[320+:64]),
        .m_cycle_id(m_cycle_id[160+:32]),
        .m_flags(m_flags[160+:32]),
        .monitor_online(device_online[5]),
        .monitor_errors(device_error[160+:32]),
        .monitor_drop_count(device_drop_count[160+:32]),
        .monitor_fifo_level(device_fifo_level[160+:32]));
    ai8_modbus_rs485 #(.SYS_CLK_HZ(SYS_CLK_HZ),.FIFO_DEPTH(FIFO_DEPTH),.SHARED_BUS(1)) u_6(
        .sys_clk(sys_clk),
        .rst_sys_n(rst_sys_n),
        .timestamp_now(timestamp_now),
        .time_sync_valid(time_sync_valid),
        .time_sync_seq(time_sync_seq),
        .cfg_valid(cfg_valid),
        .cfg_write(cfg_write),
        .cfg_addr(cfg_addr),
        .cfg_wdata(cfg_wdata),
        .cfg_wstrb(cfg_wstrb),
        .uart_rxd(bus_rxd[1]),
        .uart_txd(bus_txd[1]),
        .rs485_de(bus_de[1]),
        .bus_request(bus_request[1]),
        .bus_busy(bus_busy[1]),
        .bus_grant(bus_grant[1]),
        .cfg_ready(ready[6]),
        .cfg_error(error[6]),
        .cfg_error_code(cfg_error_code[24+:4]),
        .cfg_rdata(rdata[192+:32]),
        .m_valid(m_valid[6]),
        .m_ready(m_ready[6]),
        .m_data(m_data[192+:32]),
        .m_keep(m_keep[24+:4]),
        .m_sof(m_sof[6]),
        .m_last(m_last[6]),
        .m_source_id(m_source_id[96+:16]),
        .m_msg_id(m_msg_id[96+:16]),
        .m_timestamp(m_timestamp[384+:64]),
        .m_cycle_id(m_cycle_id[192+:32]),
        .m_flags(m_flags[192+:32]),
        .online(device_online[6]),
        .errors(device_error[192+:32]),
        .drop_count(device_drop_count[192+:32]),
        .fifo_level(device_fifo_level[192+:32]));
    i2c_arbiter_2 u_i2c_arbiter(
        .sys_clk(sys_clk),.rst_sys_n(rst_sys_n),.c_valid(i_valid),.c_ready(i_ready),
        .c_addr(i_addr),.c_write_len(i_write_len),.c_read_len(i_read_len),.c_write_data(i_write_data),
        .c_done(i_done),.c_error(i_error),.c_read_data(i_read_data),
        .req_valid(req_valid),.req_ready(req_ready),.req_addr(req_addr),
        .req_write_len(req_write_len),.req_read_len(req_read_len),.req_write_data(req_write_data),
        .done(done),.error(bus_error),.read_data(read_data));
    i2c_master #(.SYS_CLK_HZ(SYS_CLK_HZ),.I2C_HZ(100000),.TIMEOUT_TICKS(SYS_CLK_HZ/50)) u_i2c_master(
        .sys_clk(sys_clk),.rst_sys_n(rst_sys_n),.req_valid(req_valid),.req_ready(req_ready),
        .req_addr(req_addr),.req_write_len(req_write_len),.req_read_len(req_read_len),.req_write_data(req_write_data),
        .done(done),.error(bus_error),.read_data(read_data),
        .scl_i(scl_i),.sda_i(sda_i),.scl_drive_low(scl_drive_low),.sda_drive_low(sda_drive_low),.busy(busy));
endmodule
